Test installers in Dockers (#9896)
* Avoid issue with Ubuntu 21.10+ setuptools>=06

https://github.com/pypa/setuptools/issues/2956
https://gist.github.com/altendky/b852296ac520b343890c55eabc90c880

```
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
```

* corrections

* test installers in various Linux Dockers

* prep docker images with basic tools

* --no-confirm for pacman

* debug

* debug

* debug

* stop installing git

* Revert "stop installing git"

This reverts commit 4b19f1601d2de82a73fd1cae11259199348c80f6.

* checkout after installing git

* pacman wants --noconfirm

* Revert "debug"

This reverts commit e0a2aed04164eae262683f60d524af3d3633d556.

* Revert "debug"

This reverts commit 3833da281a9684389e0cfb5a3ad28104fffb3f03.

* Revert "debug"

This reverts commit 705a3c5d6b296de1970dfff29b27ff1b616a78ea.

* add bookworm

* add install.sh -a for pacman --noconfirm automated installs

* fix

* fix

* revert install_layout workaround

* Remove =3.9* from debian python3-venv installation

Already discussed this with @wallentx related to the addition in https://github.com/Chia-Network/chia-blockchain/pull/9633/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR85.

* add fedora 33 and 34

* nicer naming

* fedora not fedor

* add ubuntu:bionic

* also chia --help

* add amazon

* Amazon wants sudo

* .

* use git-core ppa for git in bionic

* less sudo

* oops